import Button from "./Sub-Components/Button";
import Chessboard from "./Chessboard";
import Game from "./Game";
import Landing from "./Landing";
import Login from "./LoginSignup/Login";
import Input from "./Sub-Components/Input";
import Signup from "./LoginSignup/Signup";
import ChessRule from "./Rule/ChessRule";
import Logout from "./LoginSignup/Logout";
import GameOver from "./GameOver";
import FischerChessRule from "./Rule/FischerChessRule";
import LeaderBoard from "./LeaderBoard";
import AtomicChessRule from "./Rule/AtomicChessRule";
import Profile from "./Profile";
export { Button, Chessboard, Game, Landing, Login, Input, Signup  , ChessRule , Logout , GameOver , FischerChessRule , LeaderBoard , AtomicChessRule  ,Profile};
